### ISSUE TITLE
[1주차][4장] 캡슐화에 대한 전반적인 부분에 대해 설명해주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#1]
캡슐화에 대한 전반적인 부분에 대해 설명해주세요

**Comment by yerim123456** [comment]
- 인스턴스 변수는 private로 선언하여 아무나 접근할 수 없게 만들고
- 해당 인스턴스 변수는 접근 지정자가 public인 getter와 setter에 의해서만 접근이 가능하게 만든 것을 말함
- setter의 경우에는, 해당 함수 안에 제한을 둬서 값을 맘대로 바꾼다고 모두 적용되지 않게끔 함

**Comment by hyojeongchoi** [comment]
- 인스턴스 변수 주변에 방어막을 쳐줌
- 아무도 인스턴스 변수를 부적절한 값으로 설정하지 못하게
- 다른 코드에서 그 데이터를 절대 직접 접근할 수 없도록, 반드시 세터 메소드로 이용할 수 있게 해줘야 함

**Comment by nusuy** [comment]
캡슐화는 외부에서 인스턴스 변수에 직접 접근하지 못하도록 하는 것입니다.
인스턴스 변수를 직접 수정, 접근하는 대신 getter와 setter를 이용합니다.
