### ISSUE TITLE
[7주차][16장] List, Set, Map

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#100]
List, Set, Map을 각각 어떤 경우 사용하는지 설명해주세요.

**Comment by hyojeongchoi** [comment]
1. List : 순서가 중요할 때 (인덱스 위치를 알고 있는 컬렉션)
2. Set: 유일성이 중요할 때 ( 중복을 허용하지 않는 컬렉션)
3. Map: 키를 가지고 뭔가를 찾는 것이 중요할 때 (키-값 쌍을 사용하는 컬렉션)
