### ISSUE TITLE
[7주차][15장] 스레드 스케줄러가 결정내리는 것 (531p)

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#101]

**Comment by yerim123456** [comment]
누가 실행중인 상태에서 실행 가능한 상태로 움직여야 할지, 언제 어떤 상황에서 스레드가 실행중인 상태를 떠나야 하는지 등의 결정은 모두 스레드 스케줄러가 내립니다. 스케줄러는 어떤 스레드가 실행되어야 하는지, 얼마나 오랫동안 실행되어야 하는지, 그리고 스케줄러에서 그 스레드를 현재 실행중인 상태에서 쫓아냈을 대 그 스레드가 어디로 가야하는지도 결정합니다.
