### ISSUE TITLE
[7주차][16장]두 객체가 같다는 상황에서 두가지의 의미를 말해주세요(594)

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#102]

**Comment by nusuy** [comment]
두 객체가 같다는 것의 의미로는 레퍼런스 동치와 객체 동치의 개념이 있습니다.

### 1. 레퍼런스 동치
- 힙에 있는 하나의 객체를 서로 다른 레퍼런스가 참조하는 경우
- 하나의 객체를 참조하기 때문에 `hashCode()`가 같습니다.

### 2. 객체 동치
- 힙에 객체가 두 개 있고, 서로 다른 두 레퍼런스가 각 객체를 참조하지만 그 두 객체가 동치인 것으로 간주할 수 있는 경우
- 객체는 다르지만, `hashCode()`가 같은 경우
- `hashCode()`와 `equals()` 메소드를 전부 오버라이드 해야 합니다.
