### ISSUE TITLE
[7주차][15장] 병행성 문제는 무엇인지 설명해주세요

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#103]

**Comment by yerim123456** [comment]
스레드 두 개 이상이 객체의 데이터 하나에 접근하게 되는 상황이다. 즉, 서로 다른 스택 두 개에서 실행되는 메소드가 객체에 있는 동일한 객체에 대한 게터 또는 세터 메소드를 호출하게 되는 문제가 생길 수 있다.  

이 문제는 스레드 두 개가 다른 상황에는 신경을 쓰지 않고 자기 생각만 하고 각자 자기가 호출할 메소드만 호출하게 되다가 객체를 원하는 상태의 값으로 만들지 못하는 문제가 생긴다.

이는 Synchronized 키워드를 사용하여 여러 개의 스레드가 코드 블록이나 전체 메서드에 접근할 수 없도록 락을 거는 것으로 해결할 수 있다.
