### ISSUE TITLE
[8주차][15장] synchronized 키워드를 이용한 객체의 락

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#104]
락이 걸리는 순간 같은 객체 내의 모든 synchronized 메소드가 함께 락이 걸리나요? (Y/N)

**Comment by yerim123456** [comment]
Y

객체의 synchronized 메소드에 접근할 때 lock이 걸리게 됩니다. synchronized 메소드는 레퍼런스 변수와 동기화된 메소드이기 때문에 객체의 다른 synchronized 메소드 또한 레퍼런스 변수에 변화를 줄 수 있어 하나의 synchronized 메소드에 락이 걸리는 순간 다른 synchronized 메소드에도 함께 락이 걸립니다.
