### ISSUE TITLE
[8주차][16장] Comparator를 이용한 객체 정렬

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#105]
Song 클래스 안에 title이라는 String 변수가 존재할 때, ArrayList<Song>을 Comparator를 사용하여 정렬하는 코드를 작성해주세요.

**Comment by hyojeongchoi** [comment]
587p
`class Titlecompare implementsComparator<Song> {
   public int compare( Song one, Song two) { return one.getTitle().compareTo(two.getTitle());`
`Titlecompare titlecompare = new Titlecompare();`
`Collections.sort(songList, titlecompare);`
