### ISSUE TITLE
[8주차][17장] JAR 파일

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#106]
JAR 파일이 무엇인지 간단하게 설명해주세요.

**Comment by hyojeongchoi** [comment]
JAR 파일은 자바 아카이브 파일임. 모든 클ㄹㅐ스를 하나로 묶을 수 있게 해 주기 떄문에 고객에게 클래스 파일 n개가 아닌 JAR 파일 하나만 넘겨줄 수 있음
