### ISSUE TITLE
[8주차][17장] 패키지명의 충돌을 막는 방법

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#107]
패키지명의 충돌을 막는 방법은 무엇인가요?

**Comment by yerim123456** [comment]
패키지 명명 방법에 따라 패키지 이름을 작성하는 것입니다. 모든 클래스에 역도메인명을 붙여주는 것입니다.

`java
com.headfirstjava.projects.Chart
`

- com.headfirstjava는 도메인명을 각각 점으로 구분하여 거꾸로 적는 식의 예시입니다.
