### ISSUE TITLE
[8주차][17장] manifest 파일

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#108]
JAR을 만들 때 작성한 manifest.txt 파일은 JAR 파일이 생성된 후에도 manifest.txt 형태 그대로 들어가나요? 아니라면 어떤 파일로 들어가나요?

**Comment by hyojeongchoi** [comment]
JAR 파일이 생성된 후 META-INF 형태로 바뀐다
