### ISSUE TITLE
[8주차][16장] 제네릭을 사용할 때와 하지 않을 때를 비교

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#109]
제네릭을 사용할 때와 하지 않을 때를 비교하여 제네릭을 사용하여 얻게 되는 이점에 대해 알려주세요.
 p.574 참고

**Comment by nusuy** [comment]
제네릭을 사용하지 않았을 때는 모든 컬렉션에 Object 유형의 객체를 아무렇게나 집어넣을 수 있기 때문에, 올바르지 않은 유형이 들어가도 잡아낼 수 없습니다. 또한 컬렉션에서 꺼낸 객체는 Object 유형으로 나오게 되기 때문에 캐스팅 시 오류가 발생할 가능성이 높아집니다. (Fish 객체로 캐스팅 시도하지만, Pumpkin 객체일 경우 오류 발생 -> 컬렉션의 원소들이 무조건 Fish 객체로만 이루어져 있다고 장담할 수 없는 상황)

제네릭이 도입되면서 형 안전성을 갖춘 컬렉션을 만들 수 있게 되었습니다.
