### ISSUE TITLE
[2주차][6장]배열과 ArrayList의 가장 크게 다른 점을 알려주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#11]

**Comment by nusuy** [comment]
기존 배열과 ArrayList 클래스는 다음과 같은 차이점이 존재합니다.

### 1. 선언
- 기존 배열: 선언 시 배열의 크기를 지정해야합니다.
- ArrayList: 크기를 동적으로 할당할 수 있습니다. (크기가 가변적)

### 2. 원소 추가
- 기존 배열: 원소를 추가할 경우, 무조건 해당 원소가 추가될 인덱스를 지정해주어야 합니다. `arr[0] = data;`
- ArrayList: 인덱스를 지정할 필요가 없습니다. `arr.add(data);`

### 3. 배열 전용 문법
- 기존 배열은 원소에 접근할 경우 `[]`를 사용해야합니다. 이는 기존 배열에서만 쓰이는 특별한 기호입니다. `arr[0]`

**Comment by yerim123456** [comment]
ArrayList는 배열과 유사한 기능을 하지만, 배열이 아닙니다.

배열은 크기를 미리 정해주고 사용해야 하는 반면, ArrayList는 필요에 따라 동적으로 크기를 바꿀 수 있습니다.

따라서,

배열: 
```String[] array = new String[5];```
ArrayList:  
```ArrayList<String> list = new ArrayList<>();```

으로 선언 방식이 다릅니다.

**Comment by nusuy** [comment]
![image](https://github.com/GDSC-SWU/2023-JAVA-Study/assets/68212300/46c299a7-4565-468e-a26b-7148250e9095)

**Comment by hyojeongchoi** [comment]
일반 배열은 크기, 유형을 정해줘야 하나 ArrayList는 저절로 커지고 작아짐
일반 배열에 객체를 집어넣을 때에는 위치를 지정해줘야 함
배열에서는 배열 전용 문법을 써야 함
