### ISSUE TITLE
[8주차][17장] 실행 가능한 JAR을 만드는 방법

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#111]
실행 가능한 JAR을 만드는 방법은 무엇인가요?

**Comment by nusuy** [comment]
1. 클래스 파일이 모두 있는지 확인
2. `manifest.txt` 파일 생성 (main() 메소드가 들어있는 클래스를 알려주는 파일)
3. jar 도구 실행하여 모든 클래스 파일과 manifest 파일이 저장된 JAR 파일 생성 (`.java` 소스 코드 파일은 들어가지 않습니다.)
