### ISSUE TITLE
[8주차][17장] 클래스의 이름이 겹치는 경우

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#112]
클래스의 이름이 겹치는 경우 어떻게 해결하는 것이 좋은지 알려주세요.

**Comment by hyojeongchoi** [comment]
패키지를 사용하는 것이 좋다. 다만 이 같은 경우에는 패키지 명이 유일할 때 클래스 이름 충돌 방지가 보장되므로 도메인명을 역순으로 쓰는 것이 좋다
