### ISSUE TITLE
[8주차][17장] 자바 웹 스타트(JWS) 애플리케이션을 만들어서 배포하는 방법

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#113]
p. 634 를 참고하여 설명해주세요.

**Comment by nusuy** [comment]
1. 실행 가능한 JAR 파일 생성
2. jnlp 파일 생성
3. 웹 서버에 JAR과 .jnlp 파일 저장
4. 웹 서버에 새로운 mime(Content-Type) 유형 추가 `application/x-java-jnlp-file`
5. .jnlp 파일에 대한 링크가 있는 웹 페이지 생성
