### ISSUE TITLE
[8주차][16장] hashCode()와 equlas()

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#114]
hashCode()와 equlas()이 뭔지, 사용에 대해서 설명해주세요

**Comment by yerim123456** [comment]
**hashCode()**
정의: 객체마다 유일한 해시코드 값을 리턴하는 함수
사용: 해당 함수를 오버라이드하여 두 개의 서로 동등한 객체에서 같은 해시코드를 리턴하도록 해 객체 동치를 확인합니다. 

**equals()**
정의: 매개변수로 참조변수를 받아서 == 연산자로 두 객체의 주소를 비교하여 같고, 다름을 판단하는 함수
사용: 해당 함수를 오버라이드하여 객체 동일성 비교뿐만 아니라 논리적 동일성을 비교하도록 만든다. 즉, 주소가 같다면 동일하다가 아닌, 값이 같다면 동등하다로 결론을 내리도록 비교하는 것이다. 

* equals()를 재정의한 클래스는 반드시 hashCode()도 재정의해야 합니다.
*equals()와 hashCode() 메소드를 전부 오버라이드 하여 객체 동치를 확인할 수 있습니다.
