### ISSUE TITLE
[8주차][16장]유형 매개변수 선언 방법

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#115]
`public <T extends Animal> void takeThing (ArrayList<T> list)` 와 `public void takeThing(ArrayList<? extends Animal> list)`는 다른 역할을 하나요? 이렇게 두 가지 방법을 사용하는 이유는?

**Comment by nusuy** [comment]
두 형태 모두 Animal 클래스를 상속받은 유형으로 구성된 목록을 매개변수로 가지는 형태로 같은 역할을 합니다.

매개변수가 여러 개인 경우 `<? extends Animal> list` 형태를 여러 번 반복하여 작성하는 것보다, `<T>`로 작성하는 것이 더 효율적이기 때문에 상황에 따라 더 효율적인 작성 방법을 택하면 됩니다.
