### ISSUE TITLE
[8주차][17장] Jar 파일이란? 쓰는 이유는?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#116]

**Comment by yerim123456** [comment]
JAR 파일은 자바 아카이브 파일입니다. pkzip 파일 유형을 기반으로 하고 있으며 모든 클래스를 하나로 묶을 수 있게 해 주기 때문에 고객에게 클래스 파일 28개를 그냥 전달하는 대신 JAR 파일 하나만 넘겨줄 수 있기에 사용합니다.
