### ISSUE TITLE
[9주차][17장]역도메인

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#119]
패키지명 앞에 도메인명을 역순으로 쓰는 이유를 적으세요

**Comment by yerim123456** [comment]
Java Package Naming Convention을 따르기 때문입니다.
네이밍 컨벤션을 따르면 자바의 패키지명은 도메인명을 역순으로 나열하는 것입니다.
이때 com이 흔한 이유는 많은 패키지가 회사들에서 만들어지기 때문에 도메인명이 com으로 끝나고, 그래서 패키지명의 시작이 com이 되는 것입니다.

**Comment by yerim123456** [comment]
Java Package Naming Convention을 따르기 때문입니다.
네이밍 컨벤션을 따르면 자바의 패키지명은 도메인명을 역순으로 나열하는 것입니다.
이때 com이 흔한 이유는 많은 패키지가 회사들에서 만들어지기 때문에 도메인명이 com으로 끝나고, 그래서 패키지명의 시작이 com이 되는 것입니다.
