### ISSUE TITLE
[2주차][6장]단락 연산자와 비단락 연산자가 무엇인지, 비단락 연산자만의 특징이 무엇인지 알려주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#12]

**Comment by yerim123456** [comment]
단락 연산자: &&, || 
비단락 연산자: &,|
비단락 연산자의 특징: JVM에서 반드시 표현식의 양쪽을 모두 확인하도록 하는 기능이 추가됨

p.185

**Comment by hyojeongchoi** [comment]
단락 연산자 (&&, || )와 비단락 (&, | )연산자는 의미는 같으나 비단락 연산자의 경우에는 왼쪽의 결과에 따라 오른쪽을 검사하지 않고 넘어가는 단락연산자와 달라 양쪽을 모두 확인하는 기능이 있다. 주로 비트 연산자라고 불린다!

**Comment by nusuy** [comment]
![image](https://github.com/GDSC-SWU/2023-JAVA-Study/assets/68212300/5be43068-cc97-4e56-8eaa-af5d03310ffd)
