### ISSUE TITLE
[9주차][17장] JWS 앱을 만들고 배포하는 과정을 설명해주세요

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#120]

**Comment by nusuy** [comment]
1. 애플리케이션을 실행 가능한 `JAR`로 만듭니다.
2. `.jnlp` 파일을 만듭니다.
3. `JAR`과 `.jnlp` 파일을 웹 서버에 저장합니다.
4. 웹 서버에 새로운 mime(Content-Type) 유형을 추가합니다.
5. `.jnlp` 파일에 대한 링크가 들어있는 웹 페이지를 만듭니다.
