### ISSUE TITLE
[9주차][18장]보조 객체란?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#121]

**Comment by yerim123456** [comment]
실제 통신 작업을 처리하는 객체입니다. 클라이언트 객체는 원격 메소드 호출하는 것 같지만 사실은 같은 힙에 들어있는 보조 객체의 메소드를 호출하는 것이고, 그 보조 객체는 소켓 및 스트림과 관련된 자질 구레한 작업을 처리해줍니다.
