### ISSUE TITLE
[9주차][부록B] 중첩과 내부의 차이점

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#123]

**Comment by yerim123456** [comment]
**중첩 클래스**
클래스 내부에 또 다른 클래스를 선언한 것을 말합니다. 중첩 클래스는 다른 클래스 내부에 선언되기 때문에, 외부 클래스의 멤버에 쉽게 접근할 수 있다는 장점이 있습니다.

**내부 클래스**
중첩 클래스 중에서 클래스 안에서만 사용하는 클래스를 말합니다. 내부 클래스는 외부 클래스의 멤버에 쉽게 접근할 수 있기 때문에, 코드의 가독성과 유지 보수성을 높일 수 있다는 장점이 있습니다.
