### ISSUE TITLE
[9주차][17장] JAR 파일

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#124]
JAR 파일이란 무엇인지 간단히 설명해주세요.

**Comment by hyojeongchoi** [comment]
JAR 파일은 자바 아카이브 파일로 모든 클래스를 하나로 묶을 수 있게 해 주기 때문에 고객에게 JAR 파일 하나만 넘겨줄 수 있습니다.
사용하기 위해서는 JAR 파일을 실행 가능한 파일로 만들어서 실해하면 됩니다
