### ISSUE TITLE
[9주차][17장] JAR의 manifest 파일

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#125]
실행 가능한 JAR 파일을 만들 때, `manifest.txt` 파일에 들어가는 내용이 무엇인가요?

**Comment by yerim123456** [comment]
기본 manifest 파일은 Manifest 버전(Manifest-version), 작성자(Created-By) 항목 내용으로 구성되어 있습니다.

**Comment by yerim123456** [comment]
기본 manifest 파일은 Manifest 버전(Manifest-version), 작성자(Created-By) 항목 내용으로 구성되어 있습니다.
