### ISSUE TITLE
[9주차][부록 B] String의 불변성

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#127]
String의 불변성이란 무엇인지 설명해주세요.

**Comment by yerim123456** [comment]
String 객체가 생성된 후 상태가 변하지 않고 계속 유지된다는 것을 의미합니다.  String 인스턴스는 한 번 생성되면 그 값을 읽기만 할 수 있고, 변경할 수는 없습니다.
