### ISSUE TITLE
[9주차][부록 B] 열거형을 사용하는 경우

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#128]
열거형을 어떤 상황에서 사용하면 좋은지 간단히 설명해주세요.

**Comment by hyojeongchoi** [comment]
변수를 static final로 정의하면 직접 상수를 만들 수도 있지만 일련의 상수들을 한꺼번에 만들어야 하는 경우에 이런 유효한 값의 집합을 열거라고 부른다.
