### ISSUE TITLE
[9주차][18장]RMI 호출과 로컬 메소드 호출의 차이점은 무엇이고 그렇기에 어떤 것을 주의해야 하나요?

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#129]

**Comment by nusuy** [comment]
RMI 호출은 네트워크를 통해 메소드를 호출하기 때문에, 네트워킹과 입출력이 관련된 작업입니다. 결국 소켓, 스트림과 연관되어 있기 때문에 클라이언트는 언제든지 예외가 발생할 수 있음을 인식해야 합니다.
