### ISSUE TITLE
[2주차][6장]패키지의 중요성을 설명해주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#13]

**Comment by hyojeongchoi** [comment]
- 프로젝트, 라이브러리를 더 용이하게 편성할 수 있음
- 동일 이름의 새로운 클래스가 생성되어서 생겨나는 충돌 문제 미연에 방지
- 보안 기능 제공( 같은 패키지게 들어있는 클래스에서만 접근 가능하므로)

**Comment by nusuy** [comment]
패키지가 중요한 이유는 다음과 같습니다.

1. 구체적인 기능에 따라 클래스를 묶을 수 있습니다.
2. 같은 이름을 가진 클래스끼리 충돌이 발생하는 문제를 방지할 수 있습니다.
3. 보안 기능을 제공할 수 있습니다.

**Comment by hyojeongchoi** [comment]
* 보안 기능을 제공한다는 말을  클래스에서 선언문, 메소드를 불러와서 사용은 가능하지만 그 클래스 자체의 코드를 수정할 수는 없다!로 이해했어!
