### ISSUE TITLE
[9주차][17장]어플리케이션 배포 방법 3가지를 알려주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#133]

**Comment by hyojeongchoi** [comment]
애플리케이션 배포 방법에는 3가지가 있다.
1. 로컬 : 애플리케이션 전체가 최종 사용자의 컴퓨터에서 실행 가능한 JAR로 배포된 독립적인 프로그램으로 실행된다.
2. 로컬과 원격의 혼합형 : 애플리케이션 일부분이 돌아가고 있는 서버와 사용자의 로컬 시스템에서 실행되면서 서버에 연결되어 작업을 처리하는 클라이언트 부분으로 나뉘어 있다.
3. 원격 : 자바 애플리케이션 전체가 서버 시스템에서 돌아간다/ 클라이언트는 웹 브라우저와 같이 자바를 사용하지 않는 방식으로 서버에 접근한다.
