### ISSUE TITLE
[2주차][2장] 객체와 클래스의 차이점

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#15]
객체와 클래스의 차이점을 간단히 설명해주세요.

**Comment by nusuy** [comment]
클래스(class)와 객체(object)는 같은 개념이 아닙니다.
클래스는 객체를 만들기 위한 청사진 입니다.

동물이라는 클래스가 존재한다면, 토끼, 강아지, 고양이 등이 하나의 객체라고 볼 수 있습니다.

**Comment by hyojeongchoi** [comment]
클래스는 설계도이고, 객체는 그 설계도(클래스)를 가지고 객체를 만든다!
클래스: 영화 제목, 장르, 평점
객체: (주식과 함께 사라지다, 비극, -2) / (바이트 클럽, 기분이 좋아지는 비극, 127)
