### ISSUE TITLE
[2주차][6장] 일반 배열과 ArrayList의 차이점

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#17]
일반 배열과 ArrayList의 차이점을 설명해주세요.

#11 참고

**Comment by hyojeongchoi** [comment]
1. 일반 배열은 크기, 유형을 정해줘야 하나 ArrayList는 저절로 커지고 작아짐
2. 일반 배열에 객체를 집어넣을 때에는 위치를 지정해줘야 함 
3. 배열에서는 배열 전용 문법을 써야 함
