### ISSUE TITLE
[2주차][3장]레퍼런스 변수에 대해 설명해주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#20]

**Comment by nusuy** [comment]
레퍼런스 변수란 메모리에 생성된 객체에 접근할 수 있는 변수를 말합니다.
단, 객체 자체가 변수에 저장되는 것은 아닙니다.

아래 코드에서, Car 객체를 생성하여 myCar라는 변수에 저장하게 되는데, 이 myCar가 레퍼런스 변수라고 할 수 있습니다.
```java
Car myCar = new Car();
```

**Comment by hyojeongchoi** [comment]
mydog.bark();  이런 식으로 호출하면 점을 기준으로 점 앞에 있는 것(mydog라는 변수로 참조할 수 있는 객체)을 이용해 점 뒤의 bark () 메소드를 호출하라!

**Comment by hyojeongchoi** [comment]
88쪽 아랫부분이 쉽게 나와있습니다!

**Comment by hyojeongchoi** [comment]
유선이가 적어준 코드 부분에서 Car 객체 자체는 변수에 저장되지 않고 Car 객체에 접근하는 방법을 나타내는 비트들이 변수에 저장된다고 했어!
근데 원시 변수는 byte x = 7; 이라고 하면  그 7 자체를 나타내는 비트들이 변수에 저장되는거야

**Comment by nusuy** [comment]
```java
Car myCar1 = new Car();
myCar1.name = "소나타";

Car myCar2 = new Car();
myCar2.name = "제네시스";

myCar1 = myCar2;

System.out.println(myCar1.name); // 소나타
```

**Comment by yerim123456** [comment]
91쪽에 c = b; 처럼 변수 b의 값을 변수 c에 대입하게 됩니다.
b에 있는 비트들을 복사해서 그 새로운 복사본을 c 변수에 집어넣게 되어 b와 c는 같은 객체를 참고하게 됩니다.
