### ISSUE TITLE
[2주차][3장]배열은 객체인가?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#21]
배열에 어떤 원소가 들어가냐에 따라서 객체인지 아닌지가 달라진다.

**Comment by yerim123456** [comment]
X
-> 배열은 어떤 원소가 들어가는 지에 상관없이 항상 객체입니다. 배열은 원시 변수의 배열이든, 객체 레퍼런스에 대한 배열이든 상관없이 항상 객체입니다.
