### ISSUE TITLE
[2주차][6장]자바 라이브러리와 인스턴스 코드와 다른 점은?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#23]
자바 라이브러리와 인스턴트 코드와 다른 점은?

**Comment by yerim123456** [comment]
실체화된 인스턴스는 메모리에 할당되기에 인스턴스 코드는 메모리를 차지하지만, 
라이브러리는 import 했다고 해서 클래스가 커지거나 코드에 추가되어 같이 컴파일되는 것은 아닙니다.
-> 그저 단순히 자바에게 클래스의 전체 이름을 알려주기 위한 도구에 불가합니다.

**Comment by hyojeongchoi** [comment]
166p [인스턴트 코드와 다른 점]
- 라이브러리는 미리 만들어진 클래스 수 백 개가 있음. 인스턴트 코드와 똑같지만 라이브러리는 모두 미리 컴파일이 된 상태로 제공된다!
- 굳이 타이핑을 하지 않아도 됨
- 그냥 쓰기만 하면 됨
