### ISSUE TITLE
[2주차][6장] ArrayList vs 배열

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#24]
ArrayList는 배열인가?
만약 아니라면 어떤 차이점이 있는가

**Comment by yerim123456** [comment]
ArrayList는 배열과 유사한 기능을 하지만, 배열이 아닙니다.

배열은 크기를 미리 정해주고 사용해야 하는 반면, ArrayList는 필요에 따라 동적으로 크기를 바꿀 수 있습니다.

따라서,

배열: 
'''String[] array = new String[5];''' 
ArrayList:  
'''ArrayList<String> list = new ArrayList<>();'''

으로 선언 방식이 다릅니다.
