### ISSUE TITLE
[2주차][6장]단락 연산자와 비단락 연산자의 차이

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#25]
단락 연산자와 비단락 연산자의 차이

**Comment by yerim123456** [comment]
#12

**Comment by hyojeongchoi** [comment]
단락 연산자 (&&, || )와 비단락 (&, | )연산자는 의미는 같으나 비단락 연산자의 경우에는 왼쪽의 결과에 따라 오른쪽을 검사하지 않고 넘어가는 단락연산자와 달라 양쪽을 모두 확인하는 기능이 있다. 주로 비트 연산자라고 불린다!
