### ISSUE TITLE
[3주차][6장] 패키지의 중요성 3가지는?

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#27]

**Comment by nusuy** [comment]
패키지의 중요성은 다음과 같습니다.
1. 종류에 따라 클래스를 패키지 단위로 묶음으로써 프로젝트와 라이브러리를 더 용이하게 편성할 수 있습니다.
2. 클래스 이름이 같을 경우 발생하는 충돌을 방지할 수 있습니다.
3. 같은 패키지 내에서의 클래스만 그 클래스의 코드를 접근할 수 있기 때문에 보안 기능을 제공할 수 있습니다.
