### ISSUE TITLE
[3주차][7장] 오버로딩과 오버라이딩의 차이점은?

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#28]

**Comment by hyojeongchoi** [comment]
오버로딩은 이름이 같고 인자 목록이 다른 메소드 두 개를 만드는 것
그래서 오버로딩된 메소드는 메소드 이름만 같을 뿐 서로 다른 메소드임 / 상속 혹은 다형성과 전혀 관계 없음
오버라이딩은 하위 클래스에서 메소드의 역할을 변경하거나 확장할 필요가 있을 때 상속받은 메소드를 새로 정의하는 것을 의미함

**Comment by nusuy** [comment]
### 오버로딩
- 메소드 이름만 같고 인자 목록이 다른 메소드를 생성하는 것입니다.
- 오버로드된 메소드는 다형성과 관계가 없습니다.

### 오버라이딩
- 하위 클래스에서 메소드를 변경 / 확장해야할 때, 상속받은 메소드를 새로 정의하는 것입니다.
- 인자 목록이 같고, 리턴 유형은 같거나 호환 가능해야 합니다.
