### ISSUE TITLE
[3주차][7장] 하위 클래스를 만들 수 없는 경우 3가지?

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#29]

**Comment by hyojeongchoi** [comment]
1. public이 아닌 클래스의 하위클래스는 그 클래스와 같은 패키지 내에서만 만들 수 있음
 2. final이라는 키워드 변경자를 사용해 클래스를 지정하면 클래스의 하위클래스를 만들 수 없다.
 - 그 클래스가 상속 계층에서 맨 아래에 있는 클래스가 됨
 3. 클래스의 생성자가 모두 private일때
