### ISSUE TITLE
[1주차][2장] 클래스와 객체의 차이는?

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#3]

**Comment by hyojeongchoi** [comment]
- 클래스는 객체를 만들기 위한 청사진
- 객체를 아직 사용하지 않은 주소록 카드에 비유한다면
- 클래스의 메소드는 특정 카드에서 하는 일에 비유할 수 있음
- 클래스 하나 - 객체 여러개 가능

**Comment by yerim123456** [comment]
- 클래스는 객체를 사용하기 위한 청사진을 말함
- 객체는 그런 클래스의 인스턴스 변수
- 이런 객체 사용의 장점 중 하나는, 같은 코드를 계속 쓰지 않아도 되는 코드 재사용성이 좋다는 것
