### ISSUE TITLE
[3주차][6장] 단락 연산자와 비단락 연산자의 차이

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#30]
185p 단락 연산자와 비단락 연산자의 차이

**Comment by nusuy** [comment]
### 단락 연산자
- 논리 연산자라고도 합니다.
- `||` 왼쪽, 오른쪽 중 하나만 참이면 true입니다. (만약 왼쪽이 true라면 오른쪽은 검사하지 않고 넘어갑니다.)
- `&&` 양쪽 모두 참이어야 true입니다.

### 비단락 연산자
- 비트 연산자라고도 합니다.
- 비트를 조작하기 위해 사용합니다.
- 부울 표현식에서 사용하면 표현식 양쪽을 모두 확인합니다.
- `|`, `&`이 있습니다.
