### ISSUE TITLE
[3주차][6장] 패키지 이름

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#32]
패키지 전체 이름이 필요한 이유는? (189p 참고)

**Comment by yerim123456** [comment]
자바에서 현재 패키지에 포함되어 있지 않은 클래스를 사용할 때, 어떤 클래스인지 알려주기 위해 전체 패키지 이름이 필요합니다.

1) import 선언문을 활용하여 어떤 클래스인지 알려주는 방법
```java
import java.util.ArrayList;
```

2) 일일이 입력해서 어떤 클래스인지 알려주는 방법
```java
java.util.ArrayList<Dog> list = new java.util.ArrayList<Dog>();
```
