### ISSUE TITLE
[3주차][7장] 오버로딩과 오버라이딩 차이점

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#33]
오버로딩과 오버라이딩 차이점은?

#28

**Comment by nusuy** [comment]
### 오버로딩
- 메소드 이름만 같고 인자 목록이 다른 메소드를 생성하는 것입니다.
- 오버로드된 메소드는 다형성과 관계가 없습니다.

### 오버라이딩
- 하위 클래스에서 메소드를 변경 / 확장해야할 때, 상속받은 메소드를 새로 정의하는 것입니다.
- 인자 목록이 같고, 리턴 유형은 같거나 호환 가능해야 합니다.
