### ISSUE TITLE
[3주차][7장] 상위 클래스와 하위 클래스의 차이점은?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#34]
상위 클래스와 하위 클래스의 차이점은?

**Comment by nusuy** [comment]
하위 클래스는 상위 클래스를 상속받은 클래스를 의미합니다.
따라서, 상위 클래스는 하위 클래스보다 더 추상적이며, 하위 클래스는 상위 클래스보다 더 구체적입니다.
