### ISSUE TITLE
[3주차][7장] 인스턴스 변수를 오버라이드 하는가? 그 이유는?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#35]
인스턴스 변수를 오버라이드 하는가? 그 이유는?

**Comment by yerim123456** [comment]
인스턴스 변수를 오버라이드 하지 않습니다. 상속을 받을 때는 메소드를 오버라이드 하여 재정의를 합니다. 


인스턴스 변수에서 특별한 행동을 정의하는 것이 아니기 때문에 오버라이드 하지 않습니다. 하위 클래스에서는 상속 받은 인스턴스 변수를 그래도 사용하고 그 값을 마음대로 선택하면 됩니다. (인스턴스 변수를 재정의를 할 필요성이 잘 없기도 합니다.)
