### ISSUE TITLE
[3주차][6장] 패키지의 목적

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#36]
패키지를 사용하는 목적은 무엇인가요?

#27

**Comment by hyojeongchoi** [comment]
1. 프로젝트 또는 라이브러리를 더 용이하게 편성할 수 있음
2. 같은 이름을 가진 클래스를 만드는 경우에 생길 수 있는 충돌 미연에 방지 가능
3. 보안 기능 제공 가능
