### ISSUE TITLE
[1주차][1장] print와 println의 차이

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#4]
**Q. System.out.print와 System.out.println의 차이?**

**Comment by nusuy** [comment]
print는 줄바꿈 없이 출력되고, println은 줄바꿈과 함께 출력됩니다.
println은 printnewline의 줄임말이라고 생각하면 됩니다.

#### 1. print
```
System.out.print("a");
System.out.print("b");
```

출력
```
ab
```

#### 2. println
```
System.out.println("a");
System.out.println("b");
```

출력
```
a
b
```
