### ISSUE TITLE
[3주차][7장] 상속 기능의 장점

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#40]
상속 기능을 활용했을 때의 장점이 무엇인가요?

**Comment by yerim123456** [comment]
1) 코드의 중복을 방지할 수 있습니다.
- 상위 클래스의 한 군데만 변경하면 나머지 모든 하위 클래스에서 변경된 기능을 활용할 수 있습니다.
2) 일련의 클래스를 위한 공통적인 규약을 정의하게 됩니다.
- 특정 상위 클래스 밑에 모여 있는 모든 클래스에, 상위 클래스에 들어있는 모든 메소드가 들어가게 할 수 있습니다.
