### ISSUE TITLE
[3주차][7장] 상속 계층이 올바른지 확인하는 방법

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#41]
상속 계층이 올바른지 확인하는 방법이 무엇인가요?

**Comment by yerim123456** [comment]
A는 B인가를 검사해보면 됩니다.

- 도형 클래스를 상속 받은 직사각형 클래스의 경우
도형 -> 직사각형 인데, 직사각형은 도형이다 라는 말이 자연스럽기에 상속 계층이 올바르다 판단할 수 있습니다.

- 동물 클래스를 상속 받은 수학책 클래스의 경우
동물 -> 수학책 인데, 수학책은 동물이다 라는 말이 자연스럽지 않기에 상속 계층이 올바르지 않다고 판단할 수 있습니다.
