### ISSUE TITLE
[4주차][8장] 유형 안전성이 무엇이며, 모든 메소드의 인자와 리턴 유형을 Object로 해도 이가 지켜지는 이유는 무엇인지 궁금합니다.

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#43]

**Comment by nusuy** [comment]
유형 안전성(type-safety)는 어떤 객체 유형에 대해 요구해야할 것을 엉뚱한 객체에 요구하는 일이 없도록 보장하는 것을 의미합니다.
모든 메소드의 인자와 리턴 유형을 Object로 해도 이가 지켜지는 이유는, Object 레퍼런스 유형을 사용하여 객체를 생성하면 자바에서는 그 객체가 Object 유형의 인스턴스를 참조하고 있다고 알고 있기 때문에, 해당 객체에서는 Object 클래스의 메소드만 호출할 수 있습니다.

이와 같은 이유로, 아래의 코드는 컴파일 오류가 발생합니다.

```java
Object obj = new Dog();
obj.bark();
```
