### ISSUE TITLE
[4주차][7장] 메소드 오버라이딩과 오버로딩의 차이점

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#44]
메소드 오버라이딩과 오버로딩의 차이점을 간단히 설명해주세요.

**Comment by yerim123456** [comment]
오버로딩은 같은 이름의 메소드를 여러 개 가지면서 매개 변수를 다르게 정의하는 것입니다.  메소드 이름은 같으나 매개변수 타입, 매개변수가 달라야 합니다.

오버라이딩은 상위 클래스가 갖고 있는 메소드를 하위 클래스에서 재정의해서 사용하는 것입니다. 메소드 이름과 매개변수 타입, 매개변수가 모두 일치해야 합니다.
