### ISSUE TITLE
[4주차][7장] 상속 범위

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#46]
Private으로 지정한 멤버는 상속 된다 / 안된다
Public으로 지정한 멤버는 상속 된다 / 안된다

**Comment by yerim123456** [comment]
Private로 지정한 멤버는 상속이 안됩니다.  부모 클래스가 지정해 놓은 Private 메소드나, 필드에 접근할 수 없으며 변경이 불가능합니다.

Public으로 지정한 멤버는 상속이 됩니다. 부모 클래스가 지정해 놓은 Public 메소드나, 필드에 편하게 접근하여 변경할 수 있습니다.
