### ISSUE TITLE
[4주차][8장] 추상 클래스와 구상 클래스의 차이

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#47]
추상 클래스와 구상 클래스의 차이점을 간단히 설명해주세요.

**Comment by hyojeongchoi** [comment]
추상 클래스는 그 클래스의 새로운 인스턴스를 만들 수 없는 클래스를 의미한다. 그렇기에 반드시 확장해야하는 클래스를 의미함
구상 클래스는 추상 클래스를 제외한 클래스를 의미한다.
