### ISSUE TITLE
[4주차][8장]다중 상속이 불가능한 이유 및 그에 대한 해결책을 알고 싶습니다.

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#48]

**Comment by hyojeongchoi** [comment]
죽음의 다이아몬드라는 문제가 발생한다.
다중 상속을 사용하면 후에 다중 상속된 메소드, 변수를 호출 했을 때 어떤 메소드가 호출될지 혹은 어떤 값을 가진 변수가 호출될지 알 수 없기 때문이다.
이에 대한 해결책은 인터페이스를 사용하는 것이다. 인터페이스는 추상 클래스와 유사한데 인터페이스가 있다면 클래스가 반드시 상속 트리 하나로부터 나오지 않아도 되기 때문이다.
