### ISSUE TITLE
[4주차][8장] 자바에서 다중 상속이 불가능한 이유

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#49]
자바에서 다중 상속이 불가능한 이유는 무엇인가요?

#48

**Comment by yerim123456** [comment]
죽음의 다이아몬드 문제 때문입니다.

예를 들어 클래스 1, 클래스 2-1, 클래스 2-2, 클래스 3 이 있다고 할 때, 클래스 1을 클래스 2-1과 클래스 2-2가 상속을 받았고, 클래스 2-1과 클래스 2-2를 클래스 3이 상속 받았다고 가정합니다. 
이때 만약 클래스 1의 메소드 1이 있는데 이를 클래스 2-1과 클래스 2-2 모두 오버라이딩 했다고 하면, 클래스 3은 어떤 메소드 1을 참조해야 하는지 고민하게 됩니다.

애매한 상황이 나올 가능성에 대비하기 위한 특별한 규칙이 필요하기 때문에 죽음의 다이아몬드를 허용하는 경우 문제가 생길 수 있습니다. 특별한 규칙이 추가되면 배우기도 힘들어지고 특별한 경우를 신경쓰는 것도 어렵기에 간단한 언어인 자바에서는 다중 상속이 불가능합니다.
