### ISSUE TITLE
[1주차][2장] 클래스의 구성은?

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#5]

**Comment by nusuy** [comment]
클래스는 객체에서 아는 것과 객체에서 하는 것으로 구성됩니다.
이 때, 객체에서 아는 것은 **인스턴스 변수**, 객체에서 하는 것은 **메소드**라고 합니다.

```java
class Car {
   String color;
   void move() {
      System.out.println("차가 이동합니다.");
   }
}
```
위에서 `color`는 인스턴스 변수, `move()`는 메소드에 해당합니다.

**Comment by hyojeongchoi** [comment]
인스턴스 변수-> 상태
메소드-> 하는 행위
