### ISSUE TITLE
[4주차][7장] 상속 규칙

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#50]
상속을 사용할 수 있는 두가지 상황을 말해주세요 ( 215p참고)

**Comment by nusuy** [comment]
1. 어떤 클래스가 다른 클래스를 더 구체화한 형식이라면 상속을 사용합니다. (A는 B다)
2. 같은 일반적 형식에 속하는 여러 클래스에서 공유해야 하는 어떤 메소드가 있다면 상속을 활용합니다.
