### ISSUE TITLE
[4주차][8장] 추상 클래스와 구상 클래스의 차이

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#52]
추상 클래스와 구상 클래스의 차이

**Comment by nusuy** [comment]
추상 클래스는 해당 클래스의 새로운 인스턴스를 만들 수 없는 클래스를 의미합니다. 따라서, 추상 클래스는 확장이 필수입니다.
구상 클래스는 추상 클래스가 아닌 클래스를 의미하며, 즉 새로운 인스턴스를 만들 수 있는 클래스를 의미합니다.
