### ISSUE TITLE
[4주차][7장] 상속 기능을 활용하면 얻는 장점 2가지를 알려주세요.

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#53]

**Comment by hyojeongchoi** [comment]
상속을 활용하면 코드가 중복되는 것을 방지할 수 있다. 또한 그 행동을 상속받은 모든 클래스에서 새로운 변동사항이 자동으로 반영되어 하위 클래스를 건드릴 필요가 없다. 일련의 클래스를 위한 공통적인 규약을 정의할 수 있다.
