### ISSUE TITLE
 [4주치][8장] 추상메소드 eat()을 선언해보시오

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#54]
추상메소드 eat()을 선언해보시오

**Comment by yerim123456** [comment]
```java
abstract public class Human{
public abstract void eat();
}
```

**Comment by nusuy** [comment]
```java
public class Human {
   public abstract void eat();
}
```

**Comment by yerim123456** [comment]
● 추상 클래스 
		 	  - 미완성 클래스
		 	  - 객체를 생성할 수 없다
		 	  - new 연산자를 직접 사용할 수 없다
		 	  - 추상메소드가 1개라도 있으면 추상클래스
		 	  - 일반메소드와 추상메소드가 같이 선언 가능하다
		 	
		 	● 추상 메소드
		 	   - 미완성 메소드
		 	   - 형식) 리턴형 함수명(매게변수);
		 	   - 매소드의 body {} 가 없는 함수
		 	   - 메소드를 선언만 해 놓음
		 	 
		 	● 인터페이스 : 추상메소드만 선언 가능하다
