### ISSUE TITLE
[4주차][8장] 추상 메소드가 필요한 이유는?

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#56]
추상 메소드가 필요한 이유를 말해보세요

**Comment by nusuy** [comment]
추상 클래스에서 하위 클래스들이 유용하게 사용할 수 있는 일반적인 코드를 전혀 만들 수 없는 경우 (즉 메소드를 구현하는 것이 어려운 경우) 실제 메소드의 구현 내용은 집어넣지 않으면서도, 하위클래스를 위한 규약의 일부를 정의할 수 있기 때문에 추상 메소드가 필요합니다.
