### ISSUE TITLE
[5주차]10장 래퍼가 무엇인가요? 어떨 때 사용하나요?

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#63]

**Comment by hyojeongchoi** [comment]
래퍼(wrapper)란 원시 형식을 객체처럼 다뤄야 할 때 포장하는 방식이다. 
그 래퍼 형식에 해당하는 원시 형식의 인스턴스 변수가 들어있는 객체이다

`int i=288;
Integer oWrap = new Interger(i);`
