### ISSUE TITLE
[5주차][9장] 지역 변수의 삶과 영역의 차이

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#64]
지역 변수의 삶과 영역 개념의 차이를 설명해주세요.

**Comment by yerim123456** [comment]
지역 변수의 삶은 스택 프레임과 연결해서 볼 수 있습니다. 지역 변수는 그 스택 프레임이 스택에 들어있는 한 살아있습니다. 즉, 메소드가 종료될 때까지는 살아있다고 할 수 있습니다.
지역 변수의 영역은 코드 내 어디에서 어디까지 존재하는가로 연결하여 볼 수 있습니다. 변수는 자신의 영역 안에서만 사용할 수 있습니다. 지역 변수의 영역은 그 변수를 선언한 메소드 내부로 제한됩니다. 그 메소드에서 다른 메소드를 호출하면 그 변수는 아직 살아있지만(삶) 원래의 메소드가 계속해서 실행되기 전까지는 영역 밖에 있기 때문에 쓸 수 없습니다(영역).
