### ISSUE TITLE
[5주차]10장 정적 변수와 인스턴스 변수의 차이가 무엇이며, 정적 변수는 주로 어떨 때 사용하나요?

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#65]

**Comment by nusuy** [comment]
먼저 정적 변수(static variable)란, 한 클래스의 모든 인스턴스에서 단 하나의 값을 가지고 공유되는 변수를 말합니다.
인스턴스 변수는 각 인스턴스마다 따로 하나씩 생성되지만, 정적 변수는 한 클래스에 속하는 모든 인스턴스에서 하나가 생성된다는 점에서 차이가 있습니다.

정적 변수는 한 클래스의 모든 인스턴스들이 공유할 하나의 변수를 생성해야할 때 사용합니다.
