### ISSUE TITLE
[5주차][10장] 일반 메소드와 정적 메소드의 차이

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#67]
일반 메소드와 정적 메소드의 차이를 설명해주세요.

**Comment by hyojeongchoi** [comment]
일반 메소드는 인스턴스 변수에 따라 메소드의 행동이 달라지지만 정적 메소드는 인스턴스 변수에 따라 행동이 달라지지 않기에 인스턴스나 객체가 필요하지않다. 클래스만 있어도 된다.

**Comment by yerim123456** [comment]
#71
