### ISSUE TITLE
[5주차][9장] 지역변수

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#68]
지역변수의 삶과 영역의 차이점

#64

**Comment by nusuy** [comment]
지역 변수의 삶은 스택 프레임이 스택에 들어있는 동안, 즉 메소드가 종료될 때까지를 의미합니다.
지역 변수의 영역은 지역 변수가 사용될 수 있는 범위인, 그 변수를 선언한 메소드 내부를 의미합니다.

따라서 다음과 같은 코드에서 go()가 실행되고 있는 시점에서는, doStuff()의 지역 변수 b의 삶은 유지되고 있지만, b는 영역 밖에 있다고 말할 수 있습니다.
```java
public void doStuff() {
   boolean b = true;
   go(4);
}

public void go(int x) {
   int z = x + 24;
}
```
