### ISSUE TITLE
[5주차][10장] Calendar 객체의 특징

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#69]
Calendar 객체의 특징을 간단하게 설명해주세요. (p.339 참고)

**Comment by hyojeongchoi** [comment]
calendar 객체는 필드에 상태를 저장할 수 있다. 또한 날짜와 시간을 증감하는 연산도 사용할 수 있다. 
날짜와 시각을 밀리초 단위로 표현할 수 있다.
