### ISSUE TITLE
[5주차][11장] 확인 예외와 미확인 예외

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#70]
확인 예외와 미확인 예외의 차이점을 설명해주세요.

**Comment by yerim123456** [comment]
컴파일러에서 항상 확인하는 Exception 유형을 '확인 예외'라고 부르는데, 정확하게 말하자면 '컴파일러에서 확인하는 예외'라고 할 수 있습니다.

컴파일러에서 확인하지 않는 예외는 RuntimeException 뿐입니다. 다른 모든 예외에 대해서는 정해진 규칙에 따라 적절한 코드를 사용해야 합니다.

* 대부분 런타임 에러는 실행 중에 어떤 조건에 문제가 생기는 경우보다는 코드의 논리에 예측 및 예방할 수 없는 방식으로 문제가 생기기에 개발과 테스트 단계에서는 그냥 일어나게 하는 것이 좋습니다. 예를 들어, try/catch 블록을 써서 애초에 일어나지 않았어야 하는 문제를 잡아서 고치는 것은 바람직하지 않습니다.
