### ISSUE TITLE
[5주차][10장] 정적 메소드 호출

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#71]
정적 메소드를 호출할 때와 정적 메소드가 아닌 메소드를 호출할 때의 차이점과 그 이유는?

**Comment by yerim123456** [comment]
가장 큰 차이점은 인스턴스를 생성하여야 하는지 ,아닌지의 차이입니다. 

정적 메소드를 호출할 때는 인스턴스를 생성하지 않아도 클래스 명으로 호출이 가능하지만, 정적 메소드가 아닌 메소드를 호출할 때는 인스턴스를 통해 호출하여야 하기 때문입니다.

이렇게 다른 이유는 정적 메소드는 인스턴스 변수의 상태에 의해 전혀 달라지지 않기 때문입니다. 인스턴스 변수의 상태에 의해 달라지지 않으니, 인스턴스 별 다른 결과를 나타낼 경우가 없기에 클래스로 호출하여도 괜찮은 것입니다. 

추가로, 이런 정적 메소드에서는 정적 변수가 아닌 변수를 사용할 수 없습니다. 또한 정적 메소드에서는 정적 메소드가 아닌 메소드도 사용할 수 없습니다. 두 가지 요건 때문에라도 정적 메소드는 클래스의 어떤 인스턴스에서든 값이 똑같습니다. 따라서 클래스 명으로 호출하는 것이 가능합니다.
