### ISSUE TITLE
[5주차][10장] final 키워드

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#72]
final키워드를 설명하시오

**Comment by nusuy** [comment]
`final` 키워드의 역할은 크게 3가지로 볼 수 있습니다.

1. 변수를 final로 지정하면, 한번 초기화된 후 그 값이 절대 바뀔 수 없도록 선언할 수 있습니다.
2. 메소드를 final로 지정하면, 그 메소드가 오버라이딩되지 않도록 선언할 수 있습니다.
3. 클래스를 final로 지정하면, 그 클래스의 하위 클래스를 생성하지 못하도록 선언할 수 있습니다. (확장이 불가능한 클래스 선언)
