### ISSUE TITLE
[5주차][10장] %연산자

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#73]
% 연산자가 의미하는 것과 예시 코드를 작성해주세요

**Comment by yerim123456** [comment]
만약, % 연산자가 format() 에서 쓰였다고 가정한다면, % 연산자는 인자가 들어갈 자리를 뜻합니다. % 기호는 다른 인자를 나타내는 변수라고 생각해야 하고, 들어가는 것은 이 메소드의 다른 인자입니다.

```java
format("%d", 42);
```
