### ISSUE TITLE
[6주차][15장] 소켓 연결_클라이언트

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#77]
소켓 연결을 하려면 서버에 대해 클라이언트는 어떤 2가지 정보를 갖고 있어야 하나요?

**Comment by hyojeongchoi** [comment]
1. 서버가 어디에 있는지 (IP주소)
2. 어떤 포트에서 돌아가고 있는지 (TCP 포트 번호)
