### ISSUE TITLE
[6주차][11장] 예외를 잡고 던지는 것

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#78]
예외를 잡는 것과 던지는 것의 차이를 얘기해주고 각각 어떻게 코드에서 나타내는지 적어주세요

**Comment by nusuy** [comment]
예외를 잡는 것은 try/catch 블록을 사용하여 던져진 예외를 잡아 처리하는 것을 말하고, 예외를 던지는 것은 새로운 예외 객체를 만들어서 예외를 발생시키는 것을 말합니다.

- 예외를 잡는 코드
```java
try {
} catch (Exception e) {
}
```

- 예외를 던지는 코드
```java
throw new Exception();
```
