### ISSUE TITLE
[6주차][14장] 자바 프로그램의 상태를 저장하는 방법

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#80]
데이터를 만들어낸 자바 프로그램에서 사용하는 방식과 데이터를 다른 프로그램에서 사용할 떄의 방식의 차이를 알려주세요

**Comment by nusuy** [comment]
#### 1. 데이터를 만들어낸 자바 프로그램에서 사용하는 경우
직렬화를 사용합니다.
#### 2. 데이터를 다른 프로그램에서도 사용하는 경우
다른 프로그램에서도 파싱할 수 있도록 적당한 구분자를 써서 일반 텍스트 파일로 저장합니다.
