### ISSUE TITLE
[6주차][11장] finally 블록

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#81]
finally 블록에 대해 설명해주세요.

**Comment by yerim123456** [comment]
예외 발생 여부와 상관 없이 무조건 실행할 코드를 집어넣는 공간입니다. try 또는 catch 블록에 return 선언문이 있어도 무조건 실행되며, 일단 흐름 제어가 finally 블록으로 갔다가 리턴됩니다.
