### ISSUE TITLE
[6주차][14장]스트림

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#82]
연결 스트림과 연쇄 스트림의 차이를 말해주세요

**Comment by nusuy** [comment]
연결 스트림은 출발지 또는 목적지(파일, 소켓 등)로의 연결을 나타냅니다.
연쇄 스트림은 혼자서 연결될 수 없고 반드시 연결 스트림에 연쇄되어야 합니다.

아래 코드에서 `fileStream`은 연결 스트림이고, `os`는 연쇄 스트림에 해당됩니다.
```java
FileOutputStream fileStream = new FileOutputStream("MyGame.ser");
ObjectOutputStream os = new ObjectOutputStream(fileStream); // 연쇄
```
