### ISSUE TITLE
[6주차][14장] 직렬화 하지 않는 인스턴스 변수

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#85]
직렬화 과정에서 어떤 인스턴스 변수만 직렬화에서 제외하고 싶다면 어떻게 해야하나요?

**Comment by yerim123456** [comment]
직렬화 될 수 있도록 선언하는 것은 Serializable을 implements 하면 됩니다.(implements한 것을 상속 받아도 직렬화 가능한 클래스가 됩니다.)
하지만 직렬화를 하지 않아야 한다면 즉, 인스턴스 변수를 저장할 수 없다면(또는 저장해선 안 된다면) 그 변수는 transient로 지정하면 됩니다.

```java
import java.io*;

class Chat implements Serializable{
   transient String currentID; // 직렬화할 때 이 변수는 저장하지 말고 넘어가라고 transient 붙임
    
    String userName; // 직렬화 과정에서 객체 상태의 일부로 저장됨
    
    ...
}

```
