### ISSUE TITLE
[6주차][14장] 연결 스트림과 연쇄 스트림

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#87]
연결 스트림과 연쇄 스트림의 차이를 설명해주세요.

**Comment by yerim123456** [comment]
연결 스트림은 출발지나 목적지(보통 파일, 네트워크 소켓 연결, 콘솔 등)에 대한 연결을 나타냅니다.

연쇄 스트림은 출발지 또는 목적지에 연결할 수 없기 떄문에 반드시 연결 스트림 또는 다른 스트림에 연쇄되어야 합니다. 

따라서 큰 차이는 직접 목적지에 연결될 수 있는지, 다른 스트림이 필요한지의 차이라고 볼 수 있습니다. 
이 차이가 나타나는 이유는 연결 스트림이 일반적으로 너무 저수준이기 때문이라고 볼 수 있습니다. 직접적으로 연결하기에는 우리가 저장하고자 하는 것이 고수준이기에 연결 스트림 1개로는 저장이 쉽지 않은 것입니다. 우리가 실제로 저장해야 하는 것은 객체이므로 더 고수준의 연쇄 스트림이 필요합니다. 따라서 보통은 다양한 연결 및 연쇄 스트림을 조합하여 사용합니다.
