### ISSUE TITLE
[6주차][15장] Socket

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#88]
Socket이란 무엇인지 간단하게 설명해주세요.

**Comment by yerim123456** [comment]
소켓은 네트워크 세계로 데이터를 내보내거나 혹은 그 세계로부터 데이터를 받기 위한 실제적인 창구 역할을 하는 것입니다. 프로세스가 데이터를 보내거나 받기 위해서는 반드시 소켓을 열어서 소켓에 데이터를 써보내거나, 소켓으로부터 데이터를 읽어들여야 합니다. 이런 소켓은 프로토콜, IP 주소, 포트 넘버로 정의됩니다.

다시 말해 소켓은 떨어져 이는 두 호스트를 연결해주는 도구로써 인터페이스의 역할을 하는데 데이터를 주고 받을 수 있는 구조체로 소켓을 통해 데이터 통로가 만들어집니다. 이러한 소켓은 역할에 따라 서버 소켓, 클라이언트 소켓으로 구분됩니다.
