### ISSUE TITLE
[7주차][15장]synchronized라는 키워드가 하는 역할과 그 키워드가 쓰이는 상황에 대해 설명해주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#91]

**Comment by nusuy** [comment]
synchronized 키워드는 메소드에 사용하고, 해당 메소드에 한 번에 한 스레드만 접근할 수 있도록 하는 역할을 합니다.
만약 은행 거래를 하는 메소드가 있는 경우, 은행 거래 도중 다른 스레드가 접근하여 값이 변경되면 병행성 문제가 유발될 수 있으므로 해당 메소드에 synchronized 키워드를 적용합니다.
