### ISSUE TITLE
[7주차][16장] 제네릭과 다형성

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#92]
`ArrayList<Animal>` 인자를 받아들이는 메소드에 Animal을 부모 클래스로 가지는 Dog 클래스가 type인 `ArraList<Dog>`을 전달해도 되나요? 
가능하다면, 가능한 이유를 불가능하다면 왜 불가능한지를 알려주세요

**Comment by hyojeongchoi** [comment]
위 코드에서는 인자가 ArrayList<Animal> 유형으로 선언되어 있기 때문에 ArrayList<Animal>만 인자로 사용할 수 있다. 
가능하게 만드려면 public <T extends Animal> void 이름(ArrayList<T> list) 이런 식으로 선언해주어야 한다.

**Comment by hyojeongchoi** [comment]
(603p 참고) Cat이 Dog 목록에 들어갈 수도 있기에 컴파일러에서는 이를 막기 위해서 컴파일시에 오류를 내고 컴파일을 해주지 않는다
- 메소드를 선언할 때 인자 유형을 ArrayList<Animal>로 선언하면 ArrayList<Animal>만 인자로 받을 수 있다. ArrayList<Dog>이나 ArrayList<Cat>은 인자로 받지 못한다
