### ISSUE TITLE
[7주차][16장]list, set, map을 어떨 때 사용하는지 나누어서 설명해주세요

### ISSUE THREAD

**Issue by yerim123456** [GDSC-SWU/2023-JAVA-Study#93]

**Comment by yerim123456** [comment]
#100

**Comment by nusuy** [comment]
### 1. List
- 순서가 중요할 때 사용합니다.
- 인덱스 위치를 알 수 있습니다.
- 값의 중복이 허용됩니다.

### 2. Set
- 유일성이 중요할 때 사용합니다.
- 값의 중복을 허용하지 않습니다.

### 3. Map
- 키를 가지고 값을 찾는 것이 중요할 때 사용합니다.
- 키-값 쌍을 사용합니다.

**Comment by hyojeongchoi** [comment]
List : 순서가 중요할 때 (인덱스 위치를 알고 있는 컬렉션)
Set: 유일성이 중요할 때 ( 중복을 허용하지 않는 컬렉션)
Map: 키를 가지고 뭔가를 찾는 것이 중요할 때 (키-값 쌍을 사용하는 컬렉션)
