### ISSUE TITLE
[7주차][14장] 역직렬화 과정

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#94]
역직렬화의 과정을 설명해주세요. (p.476 참고)

**Comment by yerim123456** [comment]
객체를 역직렬화할 때 JVM은 직렬화되었던 객체가 직렬화 당시에 가지고 있던 것과 똑같은 상태를 가지는 객체를 힙 안에 새로 만들려는 시도를 하게 됩니다.(널 또는 기본 원시값을 가지게 되는 transient로 지정된 변수는 제외)

자세한 과정은 이렇게 볼 수 있습니다.

1) 스트림으로부터 객체를 읽어옵니다.
2) JVM에서 직렬화된 객체와 함께 저장된 정보를 통해 객체의 클래스 유형을 결정합니다.
3) JVM에서 객체의 클래스를 찾아서 불러오려는 시도를 합니다. 클래스를 찾거나 불러오는 데 실패한다면 JVM에서는 예외를 던지고 역직렬화는 실패합니다.
4) 새로운 객체는 힙에 공간을 할당받지만 직렬화된 객체의 생성자는 실행되지 않습니다. 생성자가 실행된다면 객체의 상태가 원래 '새로운' 객체의 상태로 돌아갈 텐데, 그러면 안되니까요. 
5) 객체의 상속 트리에서 그 위 어딘가에 직렬화할 수 없는 클래스가 있다면 그 직렬화할 수 없는 클래스의 생성자가 실행됩니다. 일단 생성자 연쇄 호출이 시작되고 나면 멈출 수가 없기 때문에 가장 가까운 직렬화할 수 없는 클래스부터 시작해서 그 위로 있는 모든 상위클래스의 생성자에서 상태를 새로 초기화하게 됩니다.
6) 객체의 인스턴스 변수에 직렬화된 상태값이 대입됩니다. transient로 지정된 변수는 객체 레퍼런스인 경우에는 null이, 원시 변수인 경우에는 기본값(0, false 등)이 주어집니다.
