### ISSUE TITLE
[7주차][15장] 소켓 연결을 위해 서버가 알아야 할 사항

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#95]
소켓 연결을 위해 서버가 알아야 할 사항은 무엇이 있나요.

**Comment by hyojeongchoi** [comment]
1. 서버가 어디에 있는지 (IP주소)
2. 서버가 어떤 포트에서 돌아가고 있는지(TCP 포트 번호)
