### ISSUE TITLE
[7주차][15장] 스레드의 상태

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#97]
스레드의 3가지 상태를 설명해주세요.

**Comment by hyojeongchoi** [comment]
1. 새로운 스레드 -> 스레드 인스턴스가 만들어지긴 했지만 아직 시작되지 않은 상태
2. 실행 가능한 상태-> 스레드를 실행 준비가 된 상태
3. 실행중인 상태-> 현재 실행중인 상태
