### ISSUE TITLE
[7주차][14장] 연결스트림과 연쇄스트림의 차이

### ISSUE THREAD

**Issue by hyojeongchoi** [GDSC-SWU/2023-JAVA-Study#98]

**Comment by nusuy** [comment]
연결 스트림은 출발지 혹은 목적지(파일, 소켓 등에 해당)로의 연결을 나타냅니다.
연쇄 스트림은 혼자서 사용될 수 없고, 반드시 연결 스트림에 연쇄되어야 합니다.

연결 스트림은 일반적으로 너무 저수준이기 때문에, 객체를 저장할 때는 더 고수준의 연쇄 스트림이 필요합니다.
따라서 연결 스트림에 연쇄 스트림을 연쇄시켜, 자바 객체를 바이트로 저장합니다.
