### ISSUE TITLE
[7주차][16장] 레퍼런스 동치와 객체 동치

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2023-JAVA-Study#99]
레퍼런스 동치와 객체 동치에 대해 설명해주세요.

**Comment by yerim123456** [comment]
레퍼런스 동치는 힙에 있는 한 객체를 서로 다른 레퍼런스로 참조하는 경우입니다. 두 레퍼런스에 대해서 hashCode() 메소드를 호출하면 똑같은 결과가 나옵니다. 만약, 두 레퍼런스가 정말 같은 객체를 참조하고 있는지 확인해보고 싶다면 두 레퍼런스에게 == 연산자를 사용하면 됩니다.
`java
 // foo와 bar은 레퍼런스 변수입니다.

if(foo == bar){ 
    ...
}
`

객체 동치는 힙에 객체가 두 개 들어있고, 두 레퍼런스가 각 객체를 참조하지만, 그 두 객체가 동치인 것으로 간주할 수 있는 경우입니다. 이를 알기 위해선 Object 클래스로부터 상속 받은 hashCode()와 equals() 메소드를 전부 오버라이드해야 합니다.  
`java
 // foo와 bar은 레퍼런스 변수입니다.

if(foo.equals(bar) && foo.hashCode() == bar.hashCode()){
    ...
}
`

* hashCode() 메소드를 오버라이드 하지 않으면 기본적으로 객체마다 유일한 해시코드 값을 리턴하게 되기에 오버라이드 하여 두 개의 서로 동등한 객체에서 같은 해시코드를 리턴하도록 해야 합니다.
* equals() 메소드도 어떤 객체에 대해 다른 객체를 인자로 전달하면서 해당 메소드를 호출했을 때 서로 같은 것으로 간주할 객체끼리는 true를 리턴할 수 있도록 오버라이드해야 합니다.
